// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1kNchUX14rE8ohKPaUo3x6aPeupeaRTE',
    appId: '1:479652905412:web:6a08faf2f9f395fad5e491',
    messagingSenderId: '479652905412',
    projectId: 'global-chat-fa3ad',
    authDomain: 'global-chat-fa3ad.firebaseapp.com',
    storageBucket: 'global-chat-fa3ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2v76ZC1OHdsU95zrCrU2dLWjiKYYtgDQ',
    appId: '1:479652905412:android:cdc27d79ef44ba45d5e491',
    messagingSenderId: '479652905412',
    projectId: 'global-chat-fa3ad',
    storageBucket: 'global-chat-fa3ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnyAb0BRBLuHZ8FJ_h9fj70_gm30fPGuM',
    appId: '1:479652905412:ios:fcc2eae7cfb2f2f0d5e491',
    messagingSenderId: '479652905412',
    projectId: 'global-chat-fa3ad',
    storageBucket: 'global-chat-fa3ad.firebasestorage.app',
    iosBundleId: 'com.example.globalChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnyAb0BRBLuHZ8FJ_h9fj70_gm30fPGuM',
    appId: '1:479652905412:ios:fcc2eae7cfb2f2f0d5e491',
    messagingSenderId: '479652905412',
    projectId: 'global-chat-fa3ad',
    storageBucket: 'global-chat-fa3ad.firebasestorage.app',
    iosBundleId: 'com.example.globalChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1kNchUX14rE8ohKPaUo3x6aPeupeaRTE',
    appId: '1:479652905412:web:d855b164f094ca77d5e491',
    messagingSenderId: '479652905412',
    projectId: 'global-chat-fa3ad',
    authDomain: 'global-chat-fa3ad.firebaseapp.com',
    storageBucket: 'global-chat-fa3ad.firebasestorage.app',
  );
}
